[tasks.build-debug]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.build-release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["format"]

[tasks.rename-debug]
command = "cp"
args = ["target/debug/atsi", "target/debug/@"]
dependencies = ["build-debug"]

[tasks.rename-release]
command = "cp"
args = ["target/release/atsi", "target/release/@"]
dependencies = ["build-release"]

[tasks.strip-release]
command = "strip"
args = ["target/release/@"]
dependencies = ["rename-release"]

[tasks.debug]
dependencies = ["rename-debug"]

[tasks.release]
dependencies = ["strip-release"]
